import { getTranslations } from 'next-intl/server';
import Image from 'next/image';

const BASE = 'https://www.neofort.ro';

export async function generateMetadata({ params }) {
  const { locale } = await params;
  const isRo = locale === 'ro';
  return {
    title: isRo
      ? 'Servicii NEOFORT | Consultanta Imobiliara, Tamplarie PVC, Crowdfunding'
      : 'NEOFORT Services | Real Estate Consultancy, PVC Carpentry, Crowdfunding',
    description: isRo
      ? 'Serviciile NEOFORT: consultanta imobiliara, studii de fezabilitate, proiectare arhitectura, creditare bancara, finantare crowdfunding, sisteme tamplarie PVC si aluminiu.'
      : 'NEOFORT services: real estate consultancy, feasibility studies, architectural design, bank financing, crowdfunding, PVC and aluminium carpentry systems.',
    alternates: {
      canonical: `${BASE}/${locale}/${locale === 'ro' ? 'servicii' : 'services'}`,
      languages: {
        ro: `${BASE}/ro/servicii`,
        en: `${BASE}/en/services`,
        'x-default': `${BASE}/ro/servicii`,
      },
    },
    robots: { index: true, follow: true },
  };
}

export default async function ServiciiPage({ params }) {
  const { locale } = await params;
  const isRo = locale === 'ro';

  const services = [
    {
      title: isRo ? 'CONSULTANTA IMOBILIARA' : 'REAL ESTATE CONSULTANCY',
      subtitle: isRo ? 'Vanzari off-plan la preturi cu potential investitional' : 'Off-plan sales at investment potential prices',
      text: isRo
        ? 'In ultimii 5 ani portofoliul nostru de clienti a fost constituit din cumparatori si investitori ce ne-au acordat un vot consistent de incredere, astfel am atins rezultate remarcabile in zona vanzarilor off-plan. Majoritatea clientilor nostri au cumparat imobile, indiferent de proiect sau zona, la preturi discountate suficient de mult, incat multi dintre ei alegand revanzarea in detrimentul inchirierii.'
        : 'Over the last 5 years our client portfolio consisted of buyers and investors who gave us consistent trust, achieving remarkable results in off-plan sales. Most clients purchased properties at sufficiently discounted prices that many chose resale over renting.',
      img: '/images/consultanta.avif',
      imgAlt: isRo ? 'NEOFORT consultanta imobiliara Bucuresti' : 'NEOFORT real estate consultancy Bucharest',
    },
    {
      title: isRo ? 'STUDII DE FEZABILITATE' : 'FEASIBILITY STUDIES',
      subtitle: isRo ? 'Un proiect de succes se bazeaza pe profesionisti' : 'A successful project relies on professionals',
      text: isRo
        ? 'Oferim consultanta in managementul proiectului si studii de fezabilitate pentru dezvoltatori si investitori parteneri. Intr-o piata concurentiala, calculul si studiul atent legat de adresabilitatea si fezabilitatea economica a unui proiect, garanteaza intr-o masura decisiva succesul unei dezvoltari imobiliare. Mizam pe experienta acumulata in ultimii ani si marsam pe strategii preponderent prudentiale.'
        : 'We provide project management consultancy and feasibility studies for developers and partner investors. In a competitive market, careful study of addressability and economic feasibility decisively guarantees the success of a real estate development.',
      img: '/images/fezabilitate.avif',
      imgAlt: isRo ? 'NEOFORT studii fezabilitate proiecte imobiliare' : 'NEOFORT feasibility studies real estate projects',
    },
    {
      title: isRo ? 'PROIECTARE ARHITECTURA' : 'ARCHITECTURAL DESIGN',
      subtitle: isRo ? 'Oferim in parteneriate solutii la cerinte complexe de proiectare' : 'Partnership solutions for complex design requirements',
      text: isRo
        ? 'Jucatorii cu experienta din piata dezvoltarilor imobiliare cunosc cel mai bine rolul proiectarii si arhitecturii intr-o viitoare dezvoltare imobiliara. Aici putem puncta doar cateva componente: atractibilitate, versatilitate, legalitate, vandabilitate si evident continuitate. Toate acestea generate si garantate de o abordare profesionista bazata pe o experienta si expertiza verificata in timp.'
        : 'Experienced players in real estate development know best the role of design and architecture. Key components: attractiveness, versatility, legality, marketability and continuity — all generated by a professional approach based on time-tested expertise.',
      img: '/images/arhitectura.avif',
      imgAlt: isRo ? 'NEOFORT proiectare arhitectura ansambluri rezidentiale' : 'NEOFORT architectural design residential complexes',
    },
    {
      title: isRo ? 'FINANTARE PRIN CROWDFUNDING' : 'CROWDFUNDING FINANCING',
      subtitle: isRo ? 'O creditare inteligenta bazata pe principii de equity' : 'Intelligent financing based on equity principles',
      text: isRo
        ? 'Asiguram un aport consistent de finantare destinat dezvoltatorilor prin crowdfunding. Acest sistem de finantare garanteaza o solutie tangibila in a asigura o creditare usor de gestionat. Acest tip de creditare are avantajul de a imparti beneficiile operatiunii de creditare intre creditat si creditor, prin eliminarea puntilor de intermediari. Acest tip de creditare a fost testat cu succes in mai multe proiecte.'
        : 'We provide consistent financing for developers through crowdfunding. This system guarantees a tangible solution for easily manageable credit, with the advantage of sharing benefits between borrower and lender, eliminating intermediaries. Successfully tested in multiple projects.',
      img: '/images/crowdfunding.avif',
      imgAlt: isRo ? 'NEOFORT finantare crowdfunding imobiliar Romania' : 'NEOFORT real estate crowdfunding financing Romania',
    },
    {
      title: isRo ? 'CREDITARE BANCARA SI NEBANCARA' : 'BANK AND NON-BANK FINANCING',
      subtitle: isRo ? 'Asiguram solutii rapide si competitive de creditare' : 'Fast and competitive financing solutions',
      text: isRo
        ? 'Sprijinul oferit clientilor si investitorilor cumparatori in vederea obtinerii de finantare bancara si nebancara este oferit la un nivel superior de competitivitate. Prin parteneri conectati direct cu bancile si IFN-urile din piata, reusim sa gasim solutii inclusiv pentru situatii complicate. Practic incercam sa gasim solutii usoare si avantajoase pentru un client, de a obtine creditul in timpi si in conditii de pret foarte avantajoase.'
        : 'We provide bank and non-bank financing support at superior competitiveness. Through partners directly connected with banks and NBFIs, we find solutions even for complicated situations, at very advantageous timing and price conditions.',
      img: '/images/creditare.avif',
      imgAlt: isRo ? 'NEOFORT creditare bancara imobiliara Bucuresti' : 'NEOFORT bank financing real estate Bucharest',
    },
    {
      title: isRo ? 'SISTEME DE TAMPLARIE PVC & ALUMINIU' : 'PVC & ALUMINIUM CARPENTRY SYSTEMS',
      subtitle: isRo ? 'La un pret si o calitate a produselor si serviciilor greu de egalat' : 'Price and quality hard to match',
      text: isRo
        ? 'Activam in sfera furnizararii si montajului de tamplarie PVC si Aluminiu inca din 2005. In timp am devenit un furnizor notabil de tamplarie PVC Salamander din centrul si sudul tarii. Tamplaria este produsa in una dintre cele mai mari fabrici de profil din tara la standarde de calitate ce garanteaza o pondere a exporturilor de pana la 30-40%. Tamplaria furnizata de noi a ajuns in majoritatea statelor europene.'
        : 'Active in PVC and Aluminium carpentry supply and installation since 2005. We became a notable Salamander PVC carpentry supplier in central and southern Romania, with quality standards guaranteeing exports of up to 30-40% reaching most European countries.',
      img: '/images/tamplarie-servicii.avif',
      imgAlt: isRo ? 'Neofort BIZ sisteme tamplarie PVC aluminiu Romania' : 'Neofort BIZ PVC aluminium carpentry systems Romania',
      href: 'https://www.neofort-biz.ro/ro',
    },
  ];

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: isRo ? 'Servicii NEOFORT' : 'NEOFORT Services',
    itemListElement: services.map((s, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: s.title,
      description: s.text.substring(0, 160),
    })),
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Header sectiune — fundal alb, text centrat */}
      <section style={{ background: '#fff', padding: '80px 20px 40px', textAlign: 'center' }}>
        <h1 style={{
          fontFamily: 'Helvetica Neue, Helvetica, Arial, sans-serif',
          fontSize: 'clamp(20px, 3vw, 26px)',
          fontWeight: 300,
          color: '#1a1a1a',
          textTransform: 'uppercase',
          letterSpacing: '0.15em',
          marginBottom: 32,
        }}>
          {isRo ? 'SERVICII' : 'SERVICES'}
        </h1>

        {/* Rezumat text centrat — exact ca originalul */}
        <div style={{
          maxWidth: 820,
          margin: '0 auto',
          fontFamily: 'Helvetica Neue, Helvetica, Arial, sans-serif',
          fontSize: 14,
          fontWeight: 300,
          color: '#1a1a1a',
          lineHeight: 2,
          textAlign: 'center',
        }}>
          {isRo ? (
            <>
              Oferim <strong style={{ fontWeight: 700 }}>consultanta imobiliara</strong> in vederea vanzarii de apartamente in ansambluri rezidentiale proprii cat si de la parteneri.<br />
              Asiguram <strong style={{ fontWeight: 700 }}>studii de fezabilitate</strong> pentru managementul dezvoltarilor imobiliare, plan de marketing si managementul proiectului.<br />
              Acordam <strong style={{ fontWeight: 700 }}>consultanta in proiectare</strong>, <strong style={{ fontWeight: 700 }}>arhitectura</strong>, <strong style={{ fontWeight: 700 }}>design interior</strong> si <strong style={{ fontWeight: 700 }}>landscaping</strong> pentru ansambluri rezidentiale noi finalizate si in constructie.<br />
              Oferim&nbsp;<strong style={{ fontWeight: 700 }}>servicii de crowdfunding</strong>, precum si <strong style={{ fontWeight: 700 }}>consultanta pentru finantare</strong> bancara si nebancara.<br />
              Avem o mare acoperire zonala in furnizarea <a href="https://www.neofort-biz.ro/ro" target="_blank" rel="noopener noreferrer" style={{ color: '#1a1a1a', fontWeight: 700 }}>sistemelor de tamplarie Salamander</a>.
            </>
          ) : (
            <>
              We offer <strong style={{ fontWeight: 700 }}>real estate consultancy</strong> for apartment sales in own and partner residential complexes.<br />
              We provide <strong style={{ fontWeight: 700 }}>feasibility studies</strong> for real estate development management, marketing plans and project management.<br />
              We provide <strong style={{ fontWeight: 700 }}>consultancy in design, architecture, interior design</strong> and landscaping for new residential complexes.<br />
              We offer <strong style={{ fontWeight: 700 }}>crowdfunding services</strong>, as well as <strong style={{ fontWeight: 700 }}>financing consultancy</strong> for bank and non-bank credit.<br />
              We have wide regional coverage in supplying <a href="https://www.neofort-biz.ro/ro" target="_blank" rel="noopener noreferrer" style={{ color: '#1a1a1a', fontWeight: 700 }}>Salamander carpentry systems</a>.
            </>
          )}
        </div>
      </section>

      {/* Grid 3 coloane × 2 rânduri — carduri cu imagine background + text overlay jos */}
      <section style={{ background: '#f7f7f5', padding: '0 80px 80px' }}>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(3, 1fr)',
          gap: 30,
        }}>
          {services.map((service, i) => (
            <article
              key={i}
              aria-labelledby={`svc-${i}`}
              style={{
                position: 'relative',
                minHeight: 840,
                overflow: 'hidden',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'flex-end',
                background: '#1a1a1a',
              }}
            >
              {/* Imagine background */}
              <Image
                src={service.img}
                alt={service.imgAlt}
                fill
                loading={i < 3 ? 'eager' : 'lazy'}
                sizes="(max-width: 1200px) 33vw, 400px"
                style={{ objectFit: 'cover', opacity: 0.75 }}
              />

              {/* Overlay gradient jos */}
              <div style={{
                position: 'absolute',
                inset: 0,
                background: 'linear-gradient(to bottom, rgba(0,0,0,0) 30%, rgba(0,0,0,0.6) 100%)',
              }} aria-hidden="true" />

              {/* Text jos */}
              <div style={{
                position: 'relative',
                zIndex: 1,
                padding: '40px 40px 41px',
              }}>
                <h2
                  id={`svc-${i}`}
                  style={{
                    fontFamily: 'Helvetica Neue, Helvetica, Arial, sans-serif',
                    fontSize: 18,
                    fontWeight: 700,
                    color: '#fff',
                    letterSpacing: '0.02em',
                    marginBottom: 14,
                    lineHeight: 1.4,
                  }}
                >
                  {service.title}
                </h2>
                <p style={{
                  fontFamily: 'Helvetica Neue, Helvetica, Arial, sans-serif',
                  fontSize: 14,
                  fontWeight: 700,
                  color: '#fff',
                  lineHeight: 1.79,
                  marginBottom: 12,
                }}>
                  {service.subtitle}
                </p>
                <p style={{
                  fontFamily: 'Helvetica Neue, Helvetica, Arial, sans-serif',
                  fontSize: 14,
                  fontWeight: 700,
                  color: '#fff',
                  lineHeight: 1.79,
                }}>
                  {service.text}
                </p>
              </div>
            </article>
          ))}
        </div>
      </section>
    </>
  );
}
