import Image from 'next/image';

const BASE = 'https://www.neofort.ro';
const F = "'Helvetica Neue', Helvetica, Arial, sans-serif";

export async function generateMetadata({ params }) {
  const { locale } = await params;
  const isRo = locale === 'ro';
  return {
    title: isRo
      ? 'Servicii NEOFORT | Consultanta Imobiliara, Tamplarie PVC, Crowdfunding'
      : 'NEOFORT Services | Real Estate Consultancy, PVC Carpentry, Crowdfunding',
    description: isRo
      ? 'Serviciile NEOFORT: consultanta imobiliara, studii de fezabilitate, proiectare arhitectura, creditare bancara, finantare crowdfunding, sisteme tamplarie PVC si aluminiu.'
      : 'NEOFORT services: real estate consultancy, feasibility studies, architectural design, bank financing, crowdfunding, PVC and aluminium carpentry systems.',
    alternates: {
      canonical: `${BASE}/${locale}/${locale === 'ro' ? 'servicii' : 'services'}`,
      languages: { ro: `${BASE}/ro/servicii`, en: `${BASE}/en/services`, 'x-default': `${BASE}/ro/servicii` },
    },
    robots: { index: true, follow: true },
  };
}

export default async function ServiciiPage({ params }) {
  const { locale } = await params;
  const isRo = locale === 'ro';

  const row1 = [
    {
      title: isRo ? 'CONSULTANTA IMOBILIARA' : 'REAL ESTATE CONSULTANCY',
      subtitle: isRo ? 'Vanzari off-plan la preturi cu potential investitional' : 'Off-plan sales at investment potential prices',
      text: isRo
        ? 'In ultimii 5 ani portofoliul nostru de clienti a fost constituit din cumparatori si investitori ce ne-au acordat un vot consistent de incredere, astfel am atins rezultate remarcabile in zona vanzarilor off-plan. Majoritatea clientilor nostri au cumparat imobile, indiferent de proiect sau zona, la preturi discountate suficient de mult, incat multi dintre ei alegand revanzarea in detrimentul inchirierii.'
        : 'Over the last 5 years our client portfolio consisted of buyers and investors who gave us consistent trust. We achieved remarkable results in off-plan sales. Most clients purchased at sufficiently discounted prices that many chose resale over renting.',
      img: '/images/consultanta.avif',
      imgAlt: isRo ? 'NEOFORT consultanta imobiliara' : 'NEOFORT real estate consultancy',
      width: 306,
    },
    {
      title: isRo ? 'STUDII DE FEZABILITATE' : 'FEASIBILITY STUDIES',
      subtitle: isRo ? 'Un proiect de succes se bazeaza pe profesionisti' : 'A successful project relies on professionals',
      text: isRo
        ? 'Oferim consultanta in managementul proiectului si studii de fezabilitate pentru dezvoltatorii si investitorii parteneri. Intr-o piata concurentiala, calculul si studiul atent legat de adresabilitatea si fezabilitatea economica a unui proiect, garanteaza intr-o masura decisiva succesul unei dezvoltari imobiliare. Mizam pe experienta acumulata in ultimii ani si marsam pe strategii preponderent prudentiale.'
        : 'We provide project management consultancy and feasibility studies for developers and partner investors. In a competitive market, careful study of addressability and economic feasibility decisively guarantees the success of a real estate development.',
      img: '/images/fezabilitate.avif',
      imgAlt: isRo ? 'NEOFORT studii fezabilitate' : 'NEOFORT feasibility studies',
      width: 307,
    },
    {
      title: isRo ? 'PROIECTARE ARHITECTURA' : 'ARCHITECTURAL DESIGN',
      subtitle: isRo ? 'Oferim in parteneriate solutii la cerinte complexe de proiectare' : 'Partnership solutions for complex design requirements',
      text: isRo
        ? 'Jucatorii cu experienta din piata dezvoltarilor imobiliare cunosc cel mai bine rolul proiectarii si arhitecturii intr-o viitoare dezvoltare imobiliara. Aici putem puncta doar cateva componente: atractibilitate, versatilitate, legalitate, vandabilitate si evident continuitate. Toate acestea generate si garantate de o abordare profesionista bazata pe o experienta si expertiza verificata in timp.'
        : 'Experienced players in real estate development know best the role of design and architecture. Key components: attractiveness, versatility, legality, marketability and continuity — all generated by a professional approach based on time-tested expertise.',
      img: '/images/arhitectura.avif',
      imgAlt: isRo ? 'NEOFORT proiectare arhitectura' : 'NEOFORT architectural design',
      width: 307,
    },
  ];

  const row2 = [
    {
      title: isRo ? 'FINANTARE PRIN CROWDFUNDING' : 'CROWDFUNDING FINANCING',
      subtitle: isRo ? 'O creditare inteligenta bazata pe principii de equity' : 'Intelligent financing based on equity principles',
      text: isRo
        ? 'Asiguram un aport consistent de finantare destinat dezvoltatorilor prin crowdfunding. Acest sistem de finantare garanteaza o solutie tangibila in a asigura o creditare usor de gestionat. Acest tip de creditare are avantajul de a imparti beneficiile operatiunii de creditare intre creditat si creditor, prin eliminarea puntilor de intermediari. Acest tip de creditare a fost testat cu succes in mai multe proiecte.'
        : 'We provide consistent financing for developers through crowdfunding. This system guarantees a tangible, easily manageable credit solution, sharing benefits between borrower and lender, eliminating intermediaries. Successfully tested in multiple projects.',
      img: '/images/crowdfunding.avif',
      imgAlt: isRo ? 'NEOFORT finantare crowdfunding' : 'NEOFORT crowdfunding financing',
      width: 306,
    },
    {
      title: isRo ? 'CREDITARE BANCARA SI NEBANCARA' : 'BANK AND NON-BANK FINANCING',
      subtitle: isRo ? 'Asiguram solutii rapide si competitive de creditare' : 'Fast and competitive financing solutions',
      text: isRo
        ? 'Sprijinul oferit clientilor si investitorilor cumparatori in vederea obtinerii de finantare bancara si nebancara este oferit la un nivel superior de competitivitate. Prin parteneri conectati direct cu bancile si IFN-urile din piata, reusim sa gasim solutii inclusiv pentru situatii complicate. Practic incercam sa gasim solutii usoare si avantajoase pentru un client, de a obtine creditul in timpi si in conditii de pret foarte avantajoase.'
        : 'Support for clients in obtaining bank and non-bank financing is provided at superior competitiveness. Through partners directly connected with banks and NBFIs, we find solutions even for complicated situations at very advantageous price and time conditions.',
      img: '/images/creditare.avif',
      imgAlt: isRo ? 'NEOFORT creditare bancara' : 'NEOFORT bank financing',
      width: 307,
    },
    {
      title: isRo ? 'SISTEME DE TAMPLARIE PVC & ALUMINIU' : 'PVC & ALUMINIUM CARPENTRY SYSTEMS',
      subtitle: isRo ? 'La un pret si o calitate a produselor si serviciilor greu de egalat' : 'Price and quality hard to match',
      text: isRo
        ? 'Activam in sfera furnizararii si montajului de tamplarie PVC si Aluminiu inca din 2005. In timp am devenit un furnizor notabil de tamplarie PVC Salamander din centrul si sudul tarii. Tamplaria este produsa in una dintre cele mai mari fabrici de profil din tara la standarde de calitate ce garanteaza o pondere a exporturilor de pana la 30-40%. Tamplaria furnizata de noi a ajuns in majoritatea statelor europene.'
        : 'Active in PVC and Aluminium carpentry supply and installation since 2005. We became a notable Salamander PVC carpentry supplier in central and southern Romania, with quality standards guaranteeing exports of up to 30-40% reaching most European countries.',
      img: '/images/tamplarie-servicii.avif',
      imgAlt: isRo ? 'Neofort BIZ tamplarie PVC aluminiu' : 'Neofort BIZ PVC aluminium carpentry',
      width: 307,
    },
  ];

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: isRo ? 'Servicii NEOFORT' : 'NEOFORT Services',
    itemListElement: [...row1, ...row2].map((s, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: s.title,
      description: s.text.substring(0, 160),
    })),
  };

  /* Card component inline — 306/307px wide × 840px tall, text la 338px de sus */
  const Card = ({ service, index }) => (
    <article
      aria-labelledby={`svc-${index}`}
      style={{
        position: 'relative',
        width: service.width,
        height: 840,
        flexShrink: 0,
        overflow: 'hidden',
        background: '#1a1a1a',
      }}
    >
      <Image
        src={service.img}
        alt={service.imgAlt}
        fill
        loading={index < 3 ? 'eager' : 'lazy'}
        sizes="307px"
        style={{ objectFit: 'cover', opacity: 0.75 }}
      />
      {/* text block starts at 338px from top — exact din CSS Wix */}
      <div style={{
        position: 'absolute',
        top: 338,
        left: 40,
        right: 40,
        bottom: 41,
      }}>
        <h2
          id={`svc-${index}`}
          style={{
            fontFamily: F,
            fontSize: 18,
            fontWeight: 400,
            color: '#fff',
            letterSpacing: '0.02em',
            lineHeight: 1.75,
            marginBottom: 14,
          }}
        >
          {service.title}
        </h2>
        <p style={{
          fontFamily: F,
          fontSize: 14,
          fontWeight: 400,
          color: '#fff',
          lineHeight: 1.79,
          marginBottom: 14,
        }}>
          {service.subtitle}
        </p>
        <p style={{
          fontFamily: F,
          fontSize: 14,
          fontWeight: 300,
          color: '#fff',
          lineHeight: 1.79,
        }}>
          {service.text}
        </p>
      </div>
    </article>
  );

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      {/* Header alb centrat */}
      <section style={{ background: '#fff', padding: '80px 20px 40px', textAlign: 'center' }}>
        <h1 style={{ fontFamily: F, fontSize: 22, fontWeight: 200, color: '#1a1a1a', textTransform: 'uppercase', letterSpacing: '0.15em', marginBottom: 32 }}>
          {isRo ? 'SERVICII' : 'SERVICES'}
        </h1>
        <div style={{ maxWidth: 820, margin: '0 auto', fontFamily: F, fontSize: 14, fontWeight: 300, color: '#1a1a1a', lineHeight: 2 }}>
          {isRo ? (
            <>
              Oferim <strong style={{ fontWeight: 600 }}>consultanta imobiliara</strong> in vederea vanzarii de apartamente in ansambluri rezidentiale proprii cat si de la parteneri.<br />
              Asiguram <strong style={{ fontWeight: 600 }}>studii de fezabilitate</strong> pentru managementul dezvoltarilor imobiliare, plan de marketing si managementul proiectului.<br />
              Acordam <strong style={{ fontWeight: 600 }}>consultanta in proiectare</strong>, <strong style={{ fontWeight: 600 }}>arhitectura</strong>, <strong style={{ fontWeight: 600 }}>design interior</strong> si <strong style={{ fontWeight: 600 }}>landscaping</strong> pentru ansambluri rezidentiale noi.<br />
              Oferim&nbsp;<strong style={{ fontWeight: 600 }}>servicii de crowdfunding</strong>, precum si <strong style={{ fontWeight: 600 }}>consultanta pentru finantare</strong> bancara si nebancara.<br />
              Avem o mare acoperire zonala in furnizarea <a href="https://www.neofort-biz.ro/ro" target="_blank" rel="noopener noreferrer" style={{ color: '#1a1a1a', fontWeight: 600 }}>sistemelor de tamplarie Salamander</a>.
            </>
          ) : (
            <>
              We offer <strong style={{ fontWeight: 600 }}>real estate consultancy</strong> for apartment sales in own and partner residential complexes.<br />
              We provide <strong style={{ fontWeight: 600 }}>feasibility studies</strong> for real estate development management, marketing plans and project management.<br />
              We provide <strong style={{ fontWeight: 600 }}>consultancy in design, architecture, interior design</strong> and landscaping for new residential complexes.<br />
              We offer <strong style={{ fontWeight: 600 }}>crowdfunding services</strong>, as well as <strong style={{ fontWeight: 600 }}>financing consultancy</strong> for bank and non-bank credit.<br />
              We have wide regional coverage in supplying <a href="https://www.neofort-biz.ro/ro" target="_blank" rel="noopener noreferrer" style={{ color: '#1a1a1a', fontWeight: 600 }}>Salamander carpentry systems</a>.
            </>
          )}
        </div>
      </section>

      {/* Rand 1 — 3 carduri 306+307+307 = 980px cu gap 30px = container 980+60=1040, centrat */}
      <section style={{ background: '#f7f7f5', padding: '30px 0 0' }}>
        <div style={{
          display: 'flex',
          gap: 30,
          justifyContent: 'center',
          paddingLeft: 0,
          paddingRight: 0,
        }}>
          {row1.map((service, i) => (
            <Card key={i} service={service} index={i} />
          ))}
        </div>

        {/* Rand 2 */}
        <div style={{
          display: 'flex',
          gap: 30,
          justifyContent: 'center',
          paddingTop: 30,
          paddingBottom: 30,
        }}>
          {row2.map((service, i) => (
            <Card key={i + 3} service={service} index={i + 3} />
          ))}
        </div>
      </section>
    </>
  );
}
